### ISSUE TITLE
AudioTool source code?

### ISSUE THREAD

**Issue by akuukka** [vitei/Usagi#1]
I tried to get Usagi running on Mac, but rake fails immediately because the .NET program AudioTool.exe can't be used. Mono can be used on Mac, so running a simple command line .NET application should be possible, but unfortunately AudioTool.exe does seem to try to use System.Drawing stuff which probably requires Windows:

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeEngine' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeWin32Classic' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.dylib
`

When AudioTool.exe is invoked by rake, it shouldn't run any Windows graphics related code, right? But can't fix the tool without source code...

**Comment by MaverickAl** [comment]
The aim was to push out the audio tool with 0.4 (currently still focused on 0.3) but I'll bump it up on the priority list.
AudioTool.exe is actually the editor for constructing the sound banks so it's no mistake it's using the graphics code, that said it should really be split into two executables. In an ideal world we'd move away from ATF for all of the tools, but that's not immediately practical.
As a word of warning though; Mac support hasn't been a thing since pretty early in Usagi's lifetime.

**Comment by MaverickAl** [comment]
The audio tool was open sourced in 2020.
In addition in the 0.3DevelopmentBuild we removed the FSIDGenerator as the enum was no longer necessary having switched over to CRC based sound ids several years ago.
A replacement tool with additional options is currently in development.
